Adds SDLJBN_AddMappingsFromRW.
cxong/SDL_JoystickButtonNames pull request #3
Opened 2018-10-10 12:00 UTC by rainerdeyke

2018-10-10 22:00 UTC, cxong requested changes
good idea to add a RW version, but please test and try the change out first. It doesn't compile

2018-10-10 22:00 UTC, cxong commented on SDL_joystickbuttonnames.c
> +		err = "Cannot open file";
need to declare and use `err`

2018-10-10 22:00 UTC, cxong commented on SDL_joystickbuttonnames.c
> +int SDLJBN_AddMappingsFromRW(SDL_RWops *file, int freerw)
rename `file` here to `rw`

2018-10-11 04:58 UTC, rainerdeyke commented on SDL_joystickbuttonnames.c
> +		err = "Cannot open file";
> need to declare and use `err`

`err` is a static variable. I use it in a way that is consistent with how it is used elsewhere in the library.

2018-10-11 05:39 UTC, cxong commented on SDL_joystickbuttonnames.c
> +		err = "Cannot open file";
oh yeah my bad, didn't realise it was declared already

2018-10-11 06:02 UTC, merged